.\" dummy line
.TH mpiSBARS 1 " 28 January 2016"
.SH NAME
mpisbars \- a program for genome extended inexact repeats search
.SH SYNOPSIS
.B mpisbars
[parametrs] [options] file [file]
.br
.SH DESCRIPTION
.B mpiSBARS
mpisbars is a program for genome extended inexact repeats search
.SH OPTIONS
.PP
\fB\-h, \-\-help\fP print help message
.PP
\fB\-v, \-\-version\fP show current version
.SH AUTHORS
Vladislav Toigildin
.SH BUGS
Please report bugs to vladislav.toigildin@cs.msu.su
.SH SEE ALSO
Project web site at https://github.com/vladisalv/graduationWork
