#!/bin/bash

if [ -z ${FLAG+x} ]; then

test_dir=`dirname $0`

PROFILING_WINDOW=${PROFILING_WINDOW:-"250"}
STEP_PROFILING=${STEP_PROFILING:-"1"}
DECOMPOSE_WINDOW=${DECOMPOSE_WINDOW:-"250"}
STEP_DECOMPOSE=${STEP_DECOMPOSE:-"100"}
NUMBER_COEFFICIENT=${NUMBER_COEFFICIENT:-"75"}
EPS=${EPS:-"0.00001"}

OUTPUT_DIR=${OUTPUT_DIR:-"$test_dir/output/"}
OUTPUT_OUT=${OUTPUT_OUT:-"$test_dir/result/"}
INPUT_DIR=${INPUT_DIR:-"$test_dir/input/"}
INPUT_FILE1=${INPUT_FILE1:-"file50K"}

SEQUENCE1="-f $INPUT_DIR/$INPUT_FILE1"
SEQUENCE2=${INPUT_FILE2:+"-F $INPUT_DIR/$INPUT_FILE2"}

USE_MATRIX=${USE_MATRIX+"--use-matrix"}
GPU=${GPU+"--gpu"}

BLOCK=${BLOCK-"100000000"}
BLOCK=${BLOCK:+"--limit-memory $BLOCK"}

fi

DATE=`date +%F_%H-%M-%S`
POSTFIX=$INPUT_FILE1-$INPUT_FILE2-$N-$GPU-$DATE
OUTPUT_FILE_OUT=$OUTPUT_EXTRA\_out_$POSTFIX
OUTPUT_FILE_DEC=$OUTPUT_EXTRA\_dec_$POSTFIX
OUTPUT_FILE_GOM=$OUTPUT_EXTRA\_gom_$POSTFIX
OUTPUT_FILE_PIC=$OUTPUT_EXTRA\_pic_$POSTFIX
OUTPUT_FILE_ANA=$OUTPUT_EXTRA\_ana_$POSTFIX

OUTPUT_FILE_OUT=$OUTPUT_OUT/$OUTPUT_FILE_OUT

if [ -z ${FLAG+x} ]; then
    PIC=${PIC+"--image-save $OUTPUT_DIR/$OUTPUT_FILE_PIC"}
    ANALYS=${ANALYS-"--repeats-analysis-save $OUTPUT_DIR/$OUTPUT_FILE_ANA"}
else
    PIC=${PIC:+"--image-save $OUTPUT_DIR/$OUTPUT_FILE_PIC"}
    ANALYS=${ANALYS:+"--repeats-analysis-save $OUTPUT_DIR/$OUTPUT_FILE_ANA"}
fi

ARGUMENTS="--profiling-window     $PROFILING_WINDOW   \
           --step-profiling       $STEP_PROFILING     \
           --decompose-window     $DECOMPOSE_WINDOW   \
           --step-decompose       $STEP_DECOMPOSE     \
           --number-coefficient   $NUMBER_COEFFICIENT \
           --eps                  $EPS                \
           $SEQUENCE1 $SEQUENCE2 $PIC $ANALYS         \
           $GPU $USE_MATRIX $GC $GA $BLOCK"

FLAG=1
