#!/bin/bash

test_dir=`dirname $0`
NN=${NN:-"4"}
EXEC=${EXEC:-"$test_dir/../src/mpisbars"}

for N in $NN
do
    source $test_dir/arguments
    source $test_dir/MPIRUN l -n $N -o $OUTPUT_FILE_OUT $EXEC $ARGUMENTS
    sleep 1
done
